name: tuklas_pilipinas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  audioplayers: ^6.0.0
  animated_background: ^2.0.0
  soundpool: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: custom_font1
      fonts:
        - asset: assets/fonts/cfont1.otf
    - family: custom_font2
      fonts:
        - asset: assets/fonts/cfont2.ttf
    - family: custom_font3
      fonts:
        - asset: assets/fonts/cfont3.ttf

  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/image5.png
    - assets/images/image6.png
    - assets/images/image7.png
    - assets/images/image8.png
    - assets/images/image9.png
    - assets/images/talasalitaan1.png
    - assets/images/talasalitaan2.png
    - assets/images/TuklasPilipinas_LOGO.png
    - assets/sounds/game_start.mp3
    - assets/sounds/start_sfx.mp3
    - assets/sounds/select_sfx.mp3
    - assets/sounds/next.mp3
    - assets/sounds/start_screen.mp3
    - assets/sounds/quiz_start.mp3
    - assets/sounds/phantom.mp3
    - assets/sounds/layer_cake.mp3
    - assets/icons/start_icon.png
    - assets/icons/aboutus_icon.png
    - assets/icons/exit_icon.png
    - assets/bg/star.png
    - assets/bg/ans_bg.png
    - assets/bg/qs.png
    - assets/bg/bg.png
    - assets/bg/wirefence.png